on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: ./SignalsDotnet

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release Tests/TacticWar.Lib.Tests --no-build --verbosity normal
